/*!
 * gameprototyper.com runtime engine
 * http://gameprototyper.com/
 * Copyright 2011, Alexandre Martins <alemartf(at)gmail(dot)com>
 *
 * Includes Buzz HTML5 Audio Library
 * http://buzz.jaysalvat.com/
 * Copyright 2011, Jay Salvat
 * Buzz is released under the MIT license.
 */
var buzz={defaults:{autoplay:!1,duration:5E3,formats:[],loop:!1,placeholder:"--",preload:"metadata",volume:80},types:{mp3:"audio/mpeg",ogg:"audio/ogg",wav:"audio/wav",aac:"audio/aac",m4a:"audio/x-m4a"},sounds:[],el:document.createElement("audio"),sound:function(c,a){function f(d){for(var a=[],b=d.length-1,e=0;e<=b;e++)a.push({start:d.start(b),end:d.end(b)});return a}function b(d,a){var b=document.createElement("source");b.src=a;if(buzz.types[a.split(".").pop()])b.type=buzz.types[a.split(".").pop()];
d.appendChild(b)}var a=a||{},g=0,i=[],k={},e=buzz.isSupported();this.load=function(){if(!e)return this;this.sound.load();return this};this.play=function(){if(!e)return this;this.sound.play();return this};this.togglePlay=function(){if(!e)return this;this.sound.paused?this.sound.play():this.sound.pause();return this};this.pause=function(){if(!e)return this;this.sound.pause();return this};this.isPaused=function(){if(!e)return null;return this.sound.paused};this.stop=function(){if(!e)return this;this.setTime(this.getDuration());
this.sound.pause();return this};this.isEnded=function(){if(!e)return null;return this.sound.ended};this.loop=function(){if(!e)return this;this.sound.loop="loop";this.bind("ended.buzzloop",function(){this.currentTime=0;this.play()});return this};this.unloop=function(){if(!e)return this;this.sound.removeAttribute("loop");this.unbind("ended.buzzloop");return this};this.mute=function(){if(!e)return this;this.sound.muted=!0;return this};this.unmute=function(){if(!e)return this;this.sound.muted=!1;return this};
this.toggleMute=function(){if(!e)return this;this.sound.muted=!this.sound.muted;return this};this.isMuted=function(){if(!e)return null;return this.sound.muted};this.setVolume=function(d){if(!e)return this;d<0&&(d=0);d>100&&(d=100);this.volume=d;this.sound.volume=d/100;return this};this.getVolume=function(){if(!e)return this;return this.volume};this.increaseVolume=function(d){return this.setVolume(this.volume+(d||1))};this.decreaseVolume=function(d){return this.setVolume(this.volume-(d||1))};this.setTime=
function(d){if(!e)return this;this.whenReady(function(){try{this.sound.currentTime=d}catch(a){}});return this};this.getTime=function(){if(!e)return null;var d=Math.round(this.sound.currentTime*100)/100;return isNaN(d)?buzz.defaults.placeholder:d};this.setPercent=function(d){if(!e)return this;return this.setTime(buzz.fromPercent(d,this.sound.duration))};this.getPercent=function(){if(!e)return null;var d=Math.round(buzz.toPercent(this.sound.currentTime,this.sound.duration));return isNaN(d)?buzz.defaults.placeholder:
d};this.setSpeed=function(d){if(!e)return this;this.sound.playbackRate=d};this.getSpeed=function(){if(!e)return null;return this.sound.playbackRate};this.getDuration=function(){if(!e)return null;var d=Math.round(this.sound.duration*100)/100;return isNaN(d)?buzz.defaults.placeholder:d};this.getPlayed=function(){if(!e)return null;return f(this.sound.played)};this.getBuffered=function(){if(!e)return null;return f(this.sound.buffered)};this.getSeekable=function(){if(!e)return null;return f(this.sound.seekable)};
this.getErrorCode=function(){if(e&&this.sound.error)return this.sound.error.code;return 0};this.getErrorMessage=function(){if(!e)return null;switch(this.getErrorCode()){case 1:return"MEDIA_ERR_ABORTED";case 2:return"MEDIA_ERR_NETWORK";case 3:return"MEDIA_ERR_DECODE";case 4:return"MEDIA_ERR_SRC_NOT_SUPPORTED";default:return null}};this.getStateCode=function(){if(!e)return null;return this.sound.readyState};this.getStateMessage=function(){if(!e)return null;switch(this.getStateCode()){case 0:return"HAVE_NOTHING";
case 1:return"HAVE_METADATA";case 2:return"HAVE_CURRENT_DATA";case 3:return"HAVE_FUTURE_DATA";case 4:return"HAVE_ENOUGH_DATA";default:return null}};this.getNetworkStateCode=function(){if(!e)return null;return this.sound.networkState};this.getNetworkStateMessage=function(){if(!e)return null;switch(this.getNetworkStateCode()){case 0:return"NETWORK_EMPTY";case 1:return"NETWORK_IDLE";case 2:return"NETWORK_LOADING";case 3:return"NETWORK_NO_SOURCE";default:return null}};this.set=function(d,a){if(!e)return this;
this.sound[d]=a;return this};this.get=function(d){if(!e)return null;return d?this.sound[d]:this.sound};this.bind=function(d,a){if(!e)return this;for(var b=this,d=d.split(" "),c=function(d){a.call(b,d)},g=0;g<d.length;g++){var f=d[g],l=f,f=l.split(".")[0];i.push({idx:l,func:c});this.sound.addEventListener(f,c,!0)}return this};this.unbind=function(d){if(!e)return this;for(var d=d.split(" "),a=0;a<d.length;a++){var b=d[a];type=b.split(".")[0];for(var c=0;c<i.length;c++){var g=i[c].idx.split(".");if(i[c].idx==
b||g[1]&&g[1]==b.replace(".",""))this.sound.removeEventListener(type,i[c].func,!0),delete i[c]}}return this};this.bindOnce=function(d,a){if(!e)return this;var b=this;k[g++]=!1;this.bind(g+d,function(){k[g]||(k[g]=!0,a.call(b));b.unbind(g+d)})};this.trigger=function(a){if(!e)return this;for(var a=a.split(" "),b=0;b<a.length;b++)for(var c=a[b],g=0;g<i.length;g++){var f=i[g].idx.split(".");if(i[g].idx==c||f[0]&&f[0]==c.replace(".","")){var j=document.createEvent("HTMLEvents");j.initEvent(f[0],!1,!0);
this.sound.dispatchEvent(j)}}return this};this.fadeTo=function(a,b,c){function g(){setTimeout(function(){f<a&&j.volume<a?(j.setVolume(j.volume+=1),g()):f>a&&j.volume>a?(j.setVolume(j.volume-=1),g()):c instanceof Function&&c.apply(j)},i)}if(!e)return this;b instanceof Function?(c=b,b=buzz.defaults.duration):b=b||buzz.defaults.duration;var f=this.volume,i=b/Math.abs(f-a),j=this;this.play();this.whenReady(function(){g()});return this};this.fadeIn=function(a,b){if(!e)return this;return this.setVolume(0).fadeTo(100,
a,b)};this.fadeOut=function(a,b){if(!e)return this;return this.fadeTo(0,a,b)};this.fadeWith=function(a,b){if(!e)return this;this.fadeOut(b,function(){this.stop()});a.play().fadeIn(b);return this};this.whenReady=function(a){if(!e)return null;var b=this;this.sound.readyState==0?this.bind("canplay.buzzwhenready",function(){a.call(b)}):a.call(b)};if(e){for(j in buzz.defaults)a[j]=a[j]||buzz.defaults[j];this.sound=document.createElement("audio");if(c instanceof Array)for(var j in c)b(this.sound,c[j]);
else if(a.formats.length)for(j in a.formats)b(this.sound,c+"."+a.formats[j]);else b(this.sound,c);a.loop&&this.loop();if(a.autoplay)this.sound.autoplay="autoplay";this.sound.preload=a.preload===!0?"auto":a.preload===!1?"none":a.preload;this.setVolume(a.volume);buzz.sounds.push(this)}},group:function(c){function a(){for(var a=f(null,arguments),g=a.shift(),i=0;i<c.length;i++)c[i][g].apply(c[i],a)}function f(a,c){return a instanceof Array?a:Array.prototype.slice.call(c)}c=f(c,arguments);this.getSounds=
function(){return c};this.add=function(a){for(var a=f(a,arguments),g=0;g<a.length;g++)for(var i=0;i<c.length;i++)c.push(a[g])};this.remove=function(a){for(var a=f(a,arguments),g=0;g<a.length;g++)for(var i=0;i<c.length;i++)if(c[i]==a[g]){delete c[i];break}};this.load=function(){a("load");return this};this.play=function(){a("play");return this};this.togglePlay=function(){a("togglePlay");return this};this.pause=function(b){a("pause",b);return this};this.stop=function(){a("stop");return this};this.mute=
function(){a("mute");return this};this.unmute=function(){a("unmute");return this};this.toggleMute=function(){a("toggleMute");return this};this.setVolume=function(b){a("setVolume",b);return this};this.increaseVolume=function(b){a("increaseVolume",b);return this};this.decreaseVolume=function(b){a("decreaseVolume",b);return this};this.loop=function(){a("loop");return this};this.unloop=function(){a("unloop");return this};this.setTime=function(b){a("setTime",b);return this};this.setduration=function(b){a("setduration",
b);return this};this.set=function(b,c){a("set",b,c);return this};this.bind=function(b,c){a("bind",b,c);return this};this.unbind=function(b){a("unbind",b);return this};this.bindOnce=function(b,c){a("bindOnce",b,c);return this};this.trigger=function(b){a("trigger",b);return this};this.fade=function(b,c,f,k){a("fade",b,c,f,k);return this};this.fadeIn=function(b,c){a("fadeIn",b,c);return this};this.fadeOut=function(b,c){a("fadeOut",b,c);return this}},all:function(){return new buzz.group(buzz.sounds)},
isSupported:function(){return!!this.el.canPlayType},isOGGSupported:function(){return!!this.el.canPlayType&&this.el.canPlayType('audio/ogg; codecs="vorbis"')},isWAVSupported:function(){return!!this.el.canPlayType&&this.el.canPlayType('audio/wav; codecs="1"')},isMP3Supported:function(){return!!this.el.canPlayType&&this.el.canPlayType("audio/mpeg;")},isAACSupported:function(){return!!this.el.canPlayType&&(this.el.canPlayType("audio/x-m4a;")||this.el.canPlayType("audio/aac;"))},toTimer:function(c,a){h=
Math.floor(c/3600);h=isNaN(h)?"--":h>=10?h:"0"+h;m=a?Math.floor(c/60%60):Math.floor(c/60);m=isNaN(m)?"--":m>=10?m:"0"+m;s=Math.floor(c%60);s=isNaN(s)?"--":s>=10?s:"0"+s;return a?h+":"+m+":"+s:m+":"+s},fromTimer:function(c){var a=c.toString().split(":");a&&a.length==3&&(c=parseInt(a[0])*3600+parseInt(a[1])*60+parseInt(a[2]));a&&a.length==2&&(c=parseInt(a[0])*60+parseInt(a[1]));return c},toPercent:function(c,a,f){f=Math.pow(10,f||0);return Math.round(c*100/a*f)/f},fromPercent:function(c,a,f){f=Math.pow(10,
f||0);return Math.round(a/100*c*f)/f}};
soundlib={_ready:function(){},_timeout:function(){},html5Test:/^(probably|maybe)$/i};
soundlib.canPlayURL=function(b,e){var g=b.match(/\.[a-z0-9]+$/i);if(g!=null){var a=g[0].substr(1).toLowerCase(),d={mp3:['audio/mpeg; codecs="mp3"',"audio/mpeg","audio/mp3","audio/MPA","audio/mpa-robust"],mp4:['audio/mp4; codecs="mp4a.40.2"',"audio/aac","audio/x-m4a","audio/MP4A-LATM","audio/mpeg4-generic"],aac:['audio/mp4; codecs="mp4a.40.2"',"audio/aac","audio/x-m4a","audio/MP4A-LATM","audio/mpeg4-generic"],m4a:['audio/mp4; codecs="mp4a.40.2"',"audio/aac","audio/x-m4a","audio/MP4A-LATM","audio/mpeg4-generic"],
ogg:["audio/ogg; codecs=vorbis"],wav:['audio/wav; codecs="1"',"audio/wav","audio/wave","audio/x-wav"],webm:["audio/webm"],mid:["audio/mid"],rmi:["audio/rmi"]};if((e==void 0||e=="html5")&&d[a]!=void 0){var g=soundlib._createHTML5Audio(),a=d[a],f;for(f in a)if(g.canPlayType(a[f]).match(soundlib.html5Test)!=null)return!0}}return!1};soundlib._subclassResponsibility=function(){alert("Can't instantiate abstract class");return null};
soundlib._implements=function(b,e){return function(){var g=new b,a;for(a in g)this[a]=g[a];e.apply(this,arguments)}};soundlib._merge=function(b,e){var g={},a;for(a in b)b.hasOwnProperty(a)&&(g[a]=b[a]);if(e!=void 0)for(a in e)e.hasOwnProperty(a)&&(g[a]=e[a]);return g};soundlib._defaultSoundOptions={url:"",volume:0.5,timeout:1E4,ontimeout:function(){},onfinish:function(){},onstop:function(){},onpause:function(){},onplay:function(){},onresume:function(){},oncanplaythrough:function(){},onerror:function(){}};
soundlib._createHTML5Audio=function(){var b=null;try{b=new Audio}catch(e){try{b=new Audio(null)}catch(g){try{b=document.createElement("audio")}catch(a){throw Error("Can't create HTML5 Audio object: "+e.message+","+g.message+","+a.message);}}}return b};
soundlib.Sound=function(){this.destruct=function(){soundlib._subclassResponsibility()};this.clone=function(){return soundlib._subclassResponsibility()};this.play=function(){soundlib._subclassResponsibility()};this.stop=function(){soundlib._subclassResponsibility()};this.pause=function(){soundlib._subclassResponsibility()};this.resume=function(){soundlib._subclassResponsibility()};this.setVolume=function(){soundlib._subclassResponsibility()};this.getVolume=function(){return soundlib._subclassResponsibility()};
this.setPosition=function(){soundlib._subclassResponsibility()};this.getPosition=function(){return soundlib._subclassResponsibility()};this.getDuration=function(){return soundlib._subclassResponsibility()};this.isPlaying=function(){return soundlib._subclassResponsibility()}};
soundlib._SilentSound=soundlib._implements(soundlib.Sound,function(b){this.clone=function(){return new soundlib._SilentSound};this.destruct=function(){};this.play=function(){};this.stop=function(){};this.pause=function(){};this.resume=function(){};this.setVolume=function(){};this.getVolume=function(){return 0};this.setPosition=function(){};this.getPosition=function(){return 0};this.getDuration=function(){return 0};this.isPlaying=function(){return!1};b.oncanplaythrough()});
soundlib._BuzzSound=soundlib._implements(soundlib.Sound,function(b){var e=!1,g=!1,a=new buzz.sound(b.url,{preload:!0,loop:!1,autoplay:!1});a.bind("error",function(){b.onerror()}).bind("canplaythrough",function(){g||(b.oncanplaythrough(),g=!0)}).bind("ended",function(){b.onfinish();e=!1}).bind("playing",function(){b.onplay()}).bind("play",function(){b.onresume()}).bind("pause",function(){if(a.getTime()>0)b.onstop();else b.onpause()});this.clone=function(){var a=soundlib._merge(soundlib._defaultSoundOptions,
{url:b.url,volume:b.volume});return new soundlib._BuzzSound(a)};this.destruct=function(){try{a.unbind("error"),a.unbind("canplaythrough"),a.unbind("ended"),a.unbind("playing"),a.unbind("play"),a.unbind("pause")}catch(b){}a.stop();delete a};this.play=function(){a.stop();a.play();e=!0};this.stop=function(){a.stop();e=!1};this.pause=function(){a.pause();e=!1};this.resume=function(){e=!0;a.play()};this.setVolume=function(b){a.setVolume(100*b)};this.getVolume=function(){return 0.01*a.getVolume()};this.setPosition=
function(b){a.setTime(b)};this.getPosition=function(){return a.getTime()};this.getDuration=function(){return a.getDuration()};this.isPlaying=function(){return e&&!a.isEnded()}});soundlib._AudioContext=typeof AudioContext=="function"?new AudioContext:typeof webkitAudioContext=="function"?new webkitAudioContext:null;
soundlib._AudioContextSound=soundlib._implements(soundlib.Sound,function(b,e){var g=this,a=soundlib._AudioContext;if(!a)throw Error("Invalid AudioContext");var d=null,f=null,h=a.currentTime,c=0,k=null,j=0,i=!1;(function(){if(e==void 0){var c=new XMLHttpRequest;c.open("GET",b.url,!0);c.responseType="arraybuffer";c.onload=function(){a.decodeAudioData(c.response,function(c){d=a.createBufferSource();d.buffer=c;f=a.createGainNode();d.connect(f);f.connect(a.destination);b.oncanplaythrough()},function(){b.onerror()})};
c.send()}else d=a.createBufferSource(),d.buffer=e,f=a.createGainNode(),d.connect(f),f.connect(a.destination)})();k=setInterval(function(){d&&d.buffer&&i&&a.currentTime-h>=d.buffer.duration&&(j>0?g.play(j-1):(b.onfinish(),i=!1))},200);this.clone=function(){var a=soundlib._merge(soundlib._defaultSoundOptions,{url:b.url,volume:b.volume});return new soundlib._AudioContextSound(a,d.buffer)};this.destruct=function(){g.stop();clearInterval(k);delete f;delete d};this.play=function(c){var e=d.buffer;delete f;
delete d;d=a.createBufferSource();d.buffer=e;f=a.createGainNode();d.connect(f);f.connect(a.destination);j=c==void 0?0:c;h=a.currentTime;i=!0;d.noteOn(0);b.onplay()};this.stop=function(){d.noteOff(0);i=!1;b.onstop()};this.pause=function(){c=a.currentTime-h;d.noteOff(0);i=!1;b.onpause()};this.resume=function(){var e=d.buffer;delete f;delete d;d=a.createBufferSource();d.buffer=e;f=a.createGainNode();d.connect(f);f.connect(a.destination);h=a.currentTime-c;i=!0;d.noteGrainOn(0,c,d.buffer.duration-c);b.onresume()};
this.setVolume=function(a){f.gain.value=100*a*100*a};this.getVolume=function(){return Math.sqrt(f.gain.value)/100};this.setPosition=function(a){d.noteOff(0);d.noteGrainOn(0,a,d.buffer.duration-a)};this.getPosition=function(){return Math.min(d.buffer.duration,a.currentTime-h)};this.getDuration=function(){return d.buffer.duration};this.isPlaying=function(){return i}});
soundlib._HTML5Sound=soundlib._implements(soundlib.Sound,function(b,e){var g=this,a=0,d=!1,f=!1,h=!1,c=null;e==void 0?(c=soundlib._createHTML5Audio(),c.volume=b.volume,c.addEventListener("error",function(a){b.onerror(a)},!1),c.addEventListener("canplaythrough",function(){if(!d&&(d=!0,!h))b.oncanplaythrough()},!1),c.addEventListener("ended",function(){a<=0?(f=!1,b.onfinish()):g.play(a-1)},!1),setTimeout(function(){h=!0;if(!d)b.ontimeout()},b.timeout),c.autoplay=!1,c.controls=!1,c.src=b.url,c.load()):
(c=e,c.volume=b.volume,c.addEventListener("canplaythrough",function(){d=!0},!1),c.addEventListener("ended",function(){a<=0?f=!1:g.play(a-1)},!1));this.destruct=function(){try{c.pause(),c.currentTime=0}catch(a){}f=!1;delete c};this.clone=function(){var a=soundlib._merge(soundlib._defaultSoundOptions,{url:b.url,volume:b.volume});return new soundlib._HTML5Sound(a,c.cloneNode(!0))};this.play=function(e){if(d)try{if(a=e==void 0?0:e,a>=0)c.currentTime=0,c.play(),f=!0,b.onplay()}catch(g){alert("soundlib._HTML5Audio.play error: "+
g.message)}};this.stop=function(){try{c.pause(),c.currentTime=0,f=!1,b.onstop()}catch(a){}};this.pause=function(){try{c.pause(),f=!1,b.onpause()}catch(a){}};this.resume=function(){try{c.play(),f=!0,b.onresume()}catch(a){}};this.setVolume=function(a){try{c.volume=Math.max(0,Math.min(1,a))}catch(b){}};this.getVolume=function(){try{return c.volume}catch(a){return 1}};this.setPosition=function(a){try{c.currentTime=Math.max(0,Math.min(c.duration,a))}catch(b){}};this.getPosition=function(){try{return c.currentTime}catch(a){return 0}};
this.getDuration=function(){try{return c.duration}catch(a){return 0}};this.isPlaying=function(){return f}});soundlib.createSound=function(b){b=soundlib._merge(soundlib._defaultSoundOptions,b);return soundlib.canPlayURL(b.url,"html5")?soundlib._AudioContext?new soundlib._AudioContextSound(b):new soundlib._BuzzSound(b):new soundlib._SilentSound(b)};soundlib.onready=function(b){soundlib._ready=b};soundlib.ontimeout=function(b){soundlib._timeout=b};soundlib.init=function(){soundlib._ready()};
function LoadingScreen(){var b=$("#screen0").get(0),a=b.getContext("2d");this.display=function(e,c){c=Math.floor(100*Math.max(Math.min(1,c),0));$("#screen1").get(0).style.visibility="hidden";b.style.visibility="visible";a.save();a.fillStyle="#2B3856";a.fillRect(0,0,b.width,b.height);a.fillStyle="#fff";a.font="36px sans-serif";a.textAlign="center";a.textBaseline="bottom";a.fillText("Now loading...",b.width/2,b.height/2);a.fillStyle="#000";a.fillRect(b.width/2-100,b.height/2+20,200,30);var d=a.createLinearGradient(0,
b.height/2+21,0,b.height/2+51-2);d.addColorStop(0,"#2b3856");d.addColorStop(1,"#5E5A80");a.fillStyle=d;a.fillRect(b.width/2-100+1,b.height/2+21,2*c-2,28);a.fillStyle="#fff";a.font="18px sans-serif";a.textAlign="center";a.textBaseline="bottom";a.fillText(c+"%",b.width/2,b.height/2+47);a.fillStyle="#fff";a.font="11px sans-serif";a.textAlign="right";a.textBaseline="bottom";a.fillText(e,b.width-5,b.height-5);a.restore()};this.clear=function(){a.clearRect(0,0,b.width,b.height)}};
function RAM(b){if(typeof b!="number"||b<=0)throw Error("Can't initialize the memory: invalid number of memory cells");var c=Array(b);this.reset=function(){for(var a=0;a<c.length;a++)c[a]=0};this.reset();this.read=function(a){if(a<0||a>=b)throw Error("memread: out of bounds error");return c[a]};this.write=function(a,d){if(a<0||a>=b)throw Error("memwrite: out of bounds error");return c[a]=d};this.capacity=function(){return b}};
function ImageData(){var b={};this.release=function(){for(var a in b)b[a]=null;b={}};this.load=function(a,e,f){b={};var g=a.length;(function(a){if(a.length>0){var h=arguments.callee,d=a.shift(),c=(""+d.id).toLowerCase(),d=d.url;e({file:c,total:g,remaining:1+a.length});b[c]=new Image;b[c].onabort=function(){throw Error("Can't load media '"+c+"': interrupted");};b[c].onerror=function(){throw Error("Can't load media '"+c+"': read error");};b[c].onload=function(){h(a)};b[c].src=d}else f()})(a)};this.get=
function(a){a=(""+a).toLowerCase();if(a in b)return b[a];else throw Error("Can't find media '"+a+"'");}};
function AudioData(){var d={},g=1,b={0:null},f=!1;this.release=function(){for(var a in b)b[a]!=null&&(b[a].destruct(),delete b[a]);for(a in d)d[a]!=null&&(d[a].destruct(),delete d[a]);g=1;b={0:null};d={}};this.load=function(a,b,g){var k=function(){var f=a.length;(function(a,c){if(a.length>0){var i=arguments.callee,e=a.shift(),h=(""+e.id).toLowerCase(),e=e.url;b({file:h,total:f,remaining:1+a.length});soundlib.canPlayURL(e)?d[h]=soundlib.createSound({url:e,timeout:15E3,ontimeout:function(){alert("'"+
h+"' timed out!");i(a,c)},oncanplaythrough:function(){i(a,c)},onerror:function(){alert("Error while loading media '"+h+"'");i(a,c)}}):(c.push(h),i(a,c))}else{if(c.length>0){for(var e="The following audio file"+(c.length>0?"s":"")+" cannot be played by this browser:",j=0;j<c.length;j++)e+="\n* "+c[j];alert(e)}g()}})(a,[])};soundlib.html5Test=/^(probably|maybe)$/i;soundlib.onready(function(){f=!0;k()});soundlib.ontimeout(function(){f=!1;alert("Can't initialize audio.");g()});soundlib.init()};this.getVoice=
function(a){a=parseInt(a);return f&&a in b?b[a]:null};this.createVoice=function(a){if(f)if(a in d)return b[g]=d[a].clone(),g++;else alert("Can't create voice: media '"+a+"' doesn't exist!");return 0};this.destroyVoice=function(a){f&&a!=0&&a in b&&(b[a].destruct(),delete b[a])}};
function Media(){var d=[],e=[],f=new ImageData,g=new AudioData;this.imageData=function(){return f};this.audioData=function(){return g};this.release=function(){f.release();g.release()};this.load=function(i,l,m){var h=0;d=[];e=[];for(var c in i){var j=c.substr(Math.max(0,c.lastIndexOf("."))),b=function(a,b){d.push({id:a,url:b})},a=function(a,b){e.push({id:a,url:b})},b={".png":b,".jpg":b,".gif":b,".ogg":a,".mp3":a,".mp4":a,".wav":a,".mid":a,".rmi":a,".webm":a,".txt":function(){}}[j.toLowerCase()];if(b!=
void 0)b(c,i[c]);else throw Error("Can't load media '"+c+"': unsupported file format '"+j+"'");h++}var n=0,k=function(a){l({file:a.file,total:h,remaining:h-n++})};f.load(d,k,function(){g.load(e,k,m)})}};
function TableManager(){var e=this,f=0,c={};this.reset=function(){f=0;c={}};this.tableExists=function(a){return c[a]!=void 0};this.createTable=function(){var a="table#"+f++;c[a]={};return a};this.destroyTable=function(a){if(c[a]==void 0)throw Error("Can't destroy table '"+a+"': invalid table!");c[a]=void 0};this.tableSize=function(a){if(c[a]==void 0)throw Error("Can't check the table size of '"+a+"': invalid table!");var b=0,d;for(d in c[a])b++;return b};this.tableEntryExists=function(a,b){if(c[a]==
void 0)throw Error("Can't check if entry '"+b+"' of '"+a+"' exists: invalid table!");return c[a][b]!=void 0};this.removeTableEntry=function(a,b){if(c[a]==void 0)throw Error("Can't remove entry '"+b+"' of '"+a+"': invalid table!");return c[a][b]!=void 0?(obj=c[a],obj[b]="<deleted>",delete obj[b],!0):!1};this.getTableEntry=function(a,b){if(c[a]==void 0)throw Error("Can't get entry '"+b+"' of '"+a+"': invalid table!");return c[a][b]!=void 0?c[a][b]:""};this.setTableEntry=function(a,b,d){if(c[a]==void 0)throw Error("Can't set entry '"+
b+"' of '"+a+"' to '"+d+"': invalid table!");c[a][b]=d};this.cloneTable=function(a){if(c[a]==void 0)throw Error("Can't clone table '"+a+"': invalid table!");var b=e.createTable(),d;for(d in c[a])c[b][d]=c[a][d];return b};this.getTableIterator=function(a){if(c[a]==void 0)throw Error("Can't get iterator to table '"+a+"': invalid table!");var b=[],d;for(d in c[a])b.push(d);return[b,0]};this.tableIteratorIsValid=function(a,b){if(c[a]==void 0)throw Error("Can't check validity of iterator of table '"+a+
"': invalid table!");else if(b.length!=2)throw Error("tableIteratorIsValid: not a table iterator");return b[1]>=0&&b[1]<b[0].length};this.incrementTableIterator=function(a,b){if(!e.tableIteratorIsValid(a,b))throw Error("incrementTableIterator: Invalid table iterator");return[b[0],b[1]+1]};this.getKeyFromTableIterator=function(a,b){if(!e.tableIteratorIsValid(a,b))throw Error("getKeyFromTableIterator: Invalid table iterator");return b[0][b[1]]};this.getValueFromTableIterator=function(a,b){if(!e.tableIteratorIsValid(a,
b))throw Error("getValueFromTableIterator: Invalid table iterator");return c[a][b[0][b[1]]]}};
function DataMemory(c){var a=new RAM(c),d=new Media,b=new TableManager;this.ram=function(){return a};this.media=function(){return d};this.tableManager=function(){return b};this.reset=function(){a.reset();b.reset()}};
function Instruction(a,c,b){a=[a,c,b];for(c=0;c<a.length;c++)if(b=a[c],typeof b!="number"&&typeof b!="string"&&typeof b!="boolean")throw Error("Invalid machine instruction");else typeof b=="string"&&b.replace(/</g,"&lt;").replace(/>/g,"&gt;");this.opcode=a[0];this.operand1=a[1];this.operand2=a[2]};
function InstructionMemory(){var b=[];this.reset=function(){b=[]};this.get=function(a){if(a<0||a>=b.length)throw Error("Can't find instruction number "+a);return b[a]};this.push=function(a){b.push(a)}};
function Printer(){}Printer.prototype.print=function(b){var a=$("#printer").text();$("#printer").text((a!=""?a+"\n":a)+(""+b))};Printer.prototype.text=function(){return $("#printer").text()};
function VideoDevice(){var h=this,f=[],c=function(a){f.forEach(function(d){d.notify(h,a)})};this.registerObserver=function(a){a in f||f.push(a)};var e=0,b=function(){return document.getElementById("screen"+e)};this.canvas=function(){return b()};this.canvasContext=function(){return b().getContext("2d")};var a=new SingleBufferedStrategy(this),d={translationX:0,translationY:0,scaleX:1,scaleY:1,rotationAngle:0},g=function(i,b,c,g,e){d.translationX=parseFloat(i);d.translationY=parseFloat(b);d.scaleX=parseFloat(c);
d.scaleY=parseFloat(g);d.rotationAngle=parseFloat(e);i=d.scaleX;b=d.scaleY;c=Math.cos(d.rotationAngle);g=Math.sin(d.rotationAngle);a.setTransform(i*c,b*g,-i*g,b*c,d.translationX,d.translationY)};$("#screen0, #screen1").mousemove(function(a){var b=function(a){for(var b={x:0,y:0};a;a=a.offsetParent)b.x+=a.offsetLeft,b.y+=a.offsetTop;return b}(this);c({msg:"mousemove",xpos:a.pageX-b.x,ypos:a.pageY-b.y})}).mousedown(function(a){c({msg:"mousedown",button:a.which})}).mouseup(function(a){c({msg:"mouseup",
button:a.which})});this.canvasWidth=function(){return b().width};this.canvasHeight=function(){return b().height};this.setColor=function(b,d,c){a.setRGB(b,d,c)};this.setAlpha=function(b){a.setAlpha(b)};this.setCompositeOperation=function(b){a.setCompositeOperation(b)};this.setTranslation=function(a,b){g(a,b,d.scaleX,d.scaleY,d.rotationAngle)};this.setScale=function(a,b){g(d.translationX,d.translationY,a,b,d.rotationAngle)};this.setRotation=function(a){g(d.translationX,d.translationY,d.scaleX,d.scaleY,
a)};this.enableDoubleBuffering=function(){a.isDoubleBufferingEnabled()||(b=function(){return document.getElementById("screen"+(1-e))},a=new DoubleBufferedStrategy(this),c({msg:"enabled double buffering"}))};this.disableDoubleBuffering=function(){a.isDoubleBufferingEnabled()&&(b=function(){return document.getElementById("screen"+e)},a=new SingleBufferedStrategy(this),c({msg:"disabled double buffering"}))};this.isDoubleBufferingEnabled=function(){return a.isDoubleBufferingEnabled()};this.flip=function(){if(a.isDoubleBufferingEnabled())c({msg:"aboutToFlip"}),
b().style.visibility="visible",e=1-e,b().style.visibility="hidden",c({msg:"flipped"})};this.cls=function(){a.cls()};this.drawImage=function(b,d,c){a.drawImage(b,d,c)};this.drawScaledImage=function(b,d,c,g,e){a.drawScaledImage(b,d,c,g,e)};this.drawClippedImage=function(b,d,c,g,e,f,h,n,o){a.drawClippedImage(b,d,c,g,e,f,h,n,o)};this.textout=function(b,d,c,g,e){a.textout(b,d,c,g,e)};this.rectfill=function(b,d,c,g){a.rectfill(b,d,c,g)};this.rect=function(b,d,c,g){a.rect(b,d,c,g)};this.circlefill=function(b,
d,c){a.circlefill(b,d,c)};this.circle=function(b,d,c){a.circle(b,d,c)};this.line=function(b,d,c,g){a.line(b,d,c,g)};this.reset=function(){h.disableDoubleBuffering();$("#screen0, #screen1").each(function(b,a){var d=a.getContext("2d");d.fillStyle=d.strokeStyle="rgba(255,255,255,1)";d.setTransform(1,0,0,1,0,0);d.clearRect(0,0,a.width,a.height);a.style.visibility="hidden"});e=0;b().style.visibility="visible"};this.reset()}
function SingleBufferedStrategy(h){var f=h.canvas(),c=h.canvasContext();this.isDoubleBufferingEnabled=function(){return!1};this.cls=function(){c.save();c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,f.width,f.height);c.restore()};this.setRGB=function(e,b,a){c.fillStyle=c.strokeStyle="rgb("+e+","+b+","+a+")"};this.setAlpha=function(e){c.globalAlpha=e};this.setTransform=function(e,b,a,d,g,i){c.setTransform(e,b,a,d,g,i)};this.drawImage=function(e,b,a){c.drawImage(e,b,a)};this.drawScaledImage=function(e,
b,a,d,g){c.drawImage(e,b,a,d,g)};this.drawClippedImage=function(e,b,a,d,g,i,j,f,h){c.drawImage(e,b,a,d,g,i,j,f,h)};this.textout=function(e,b,a,d,g){c.font=b+"pt "+e;c.textBaseline="top";c.fillText(g,a+0.5,d+0.5)};this.rectfill=function(e,b,a,d){c.beginPath();c.rect(e+0.5,b+0.5,a,d);c.closePath();c.fill()};this.rect=function(e,b,a,d){c.beginPath();c.rect(e+0.5,b+0.5,a,d);c.closePath();c.stroke()};this.circlefill=function(e,b,a){c.beginPath();c.arc(e+0.5,b+0.5,a,0,2*Math.PI,!0);c.closePath();c.fill()};
this.circle=function(e,b,a){c.beginPath();c.arc(e+0.5,b+0.5,a,0,2*Math.PI,!0);c.closePath();c.stroke()};this.line=function(e,b,a,d){c.beginPath();c.moveTo(e+0.5,b+0.5);c.lineTo(a+0.5,d+0.5);c.closePath();c.stroke()}}
function DoubleBufferedStrategy(h){var f=[],c=function(b,a){f.push({type:b,execute:a})},e=function(b,a){var d={fill:{start:function(){a.beginPath()},finish:function(){a.closePath();a.fill()}},stroke:{start:function(){a.beginPath()},finish:function(){a.closePath();a.stroke()}},justDoIt:{start:function(){},finish:function(){}}};(function(){var c="",e="",j;for(j in f){var h=f[j],e=h.type;e!=c&&(c in d&&d[c].finish(),e in d&&d[e].start());h.execute(b,a);c=e}e in d&&d[e].finish()})();f=[]};h.registerObserver(this);
this.notify=function(b,a){a.msg=="aboutToFlip"&&e(b.canvas(),b.canvasContext())};this.isDoubleBufferingEnabled=function(){return!0};this.cls=function(){c("justDoIt",function(b,a){a.save();a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,b.width,b.height);a.restore()})};this.setRGB=function(b,a,d){c("justDoIt",function(c,e){var j="rgb("+b+","+a+","+d+")";e.fillStyle=j;e.strokeStyle=j})};this.setAlpha=function(b){c("justDoIt",function(a,d){d.globalAlpha=b})};this.setCompositeOperation=function(b){c("justDoIt",
function(a,d){d.globalCompositeOperation=b})};this.setTransform=function(b,a,d,e,i,j){c("justDoIt",function(c,f){f.setTransform(b,a,d,e,i,j)})};this.drawImage=function(b,a,d){c("justDoIt",function(c,e){e.drawImage(b,a,d)})};this.drawScaledImage=function(b,a,d,e,i){c("justDoIt",function(c,f){f.drawImage(b,a,d,e,i)})};this.drawClippedImage=function(b,a,d,e,i,f,h,k,l){c("justDoIt",function(c,m){m.drawImage(b,a,d,e,i,f,h,k,l)})};this.textout=function(b,a,d,e,i){c("justDoIt",function(c,f){f.font=a+"pt "+
b;f.textBaseline="top";f.fillText(i,d+0.5,e+0.5)})};this.rectfill=function(b,a,d,e){c("fill",function(c,f){f.rect(b+0.5,a+0.5,d,e)})};this.rect=function(b,a,d,e){c("stroke",function(c,f){f.rect(b+0.5,a+0.5,d,e)})};this.circlefill=function(b,a,d){c("fill",function(c,e){e.arc(b+0.5,a+0.5,d,0,2*Math.PI,!0)})};this.circle=function(b,a,d){c("stroke",function(c,e){e.arc(b+0.5,a+0.5,d,0,2*Math.PI,!0)})};this.line=function(b,a,d,e){c("stroke",function(c,f){f.moveTo(b+0.5,a+0.5);f.lineTo(d+0.5,e+0.5)})}};
function AudioDevice(){this.play=function(a,b){a!=null&&a.play(b<0?9999999:b)};this.stop=function(a){a!=null&&a.stop()};this.pause=function(a){a!=null&&a.pause()};this.resume=function(a){a!=null&&a.resume()};this.setPosition=function(a,b){a!=null&&a.setPosition(b)};this.getPosition=function(a){return a!=null?a.getPosition():0};this.setVolume=function(a,b){a!=null&&a.setVolume(b)};this.getVolume=function(a){return a!=null?a.getVolume(a):0.5};this.getDuration=function(a){return a!=null?a.getDuration():
0};this.isPlaying=function(a){return a!=null?a.isPlaying():!1}};
function Keyboard(b){var c=this;this.baseAddress=function(){return 304};for(var d=0;d<512;d++)b.write(c.baseAddress()+d,!1);$(document).keydown(function(a){a=Math.max(0,Math.min(255,a.which));b.write(c.baseAddress()+a,!0)});$(document).keyup(function(a){a=Math.max(0,Math.min(255,a.which));b.write(c.baseAddress()+a,!1)});this.notify=function(a,d){switch(d.msg){case "flipped":for(var e=0;e<256;e++)b.write(c.baseAddress()+e+256,b.read(c.baseAddress()+e))}}};
function Mouse(b){var c=this;this.baseAddress=function(){return 144};this.notify=function(e,d){switch(d.msg){case "mousemove":b.write(c.baseAddress()+0,d.xpos);b.write(c.baseAddress()+1,d.ypos);break;case "mousedown":var a=Math.min(3,Math.max(1,d.button));b.write(c.baseAddress()+2+(a-1),!0);break;case "mouseup":a=Math.min(3,Math.max(1,d.button));b.write(c.baseAddress()+2+(a-1),!1);break;case "flipped":for(a=0;a<5;a++)b.write(c.baseAddress()+5+a,b.read(c.baseAddress()+a))}}};
function IO(a){var e=new Printer,b=new VideoDevice(a.ram()),f=new AudioDevice(a.ram()),c=new Keyboard(a.ram()),d=new Mouse(a.ram());b.registerObserver(d);b.registerObserver(c);this.printer=function(){return e};this.video=function(){return b};this.audio=function(){return f};this.keyboard=function(){return c};this.mouse=function(){return d}};
function Registers(){var c={PC:0,SP:1,BP:2,CPF:3,ADR:4,FUN:5,A:6,B:7,C:8,D:9},b=Array(10);this.reset=function(){for(var a=0;a<b.length;a++)b[a]=0};this.read=function(a){return b[a]};this.write=function(a,c){return b[a]=c};this.getCode=function(a){if(c[a]==void 0)throw Error("Invalid register name");return c[a]};this.bank=b;this.reset()};
function DPU(){function e(){}function c(){}function d(){}e.prototype.lcmp=function(a,b){return(a?1:0)-(b?1:0)};e.prototype.lor=function(a,b){return a||b};e.prototype.land=function(a,b){return a&&b};e.prototype.lxor=function(a,b){return!a&&b||a&&!b};e.prototype.lnot=function(a){return!a};c.prototype.fcmp=function(a,b){return a-b};c.prototype.fadd=function(a,b){return a+b};c.prototype.fsub=function(a,b){return a-b};c.prototype.fmul=function(a,b){return a*b};c.prototype.fdiv=function(a,b){return b==
0?Infinity:a/b};c.prototype.fmod=function(a,b){return a-b*Math.floor(this.fdiv(a,b))};c.prototype.fneg=function(a){return-a};c.prototype.fint=function(a){return Math.floor(a)};c.prototype.facos=function(a){return Math.acos(a)};c.prototype.fasin=function(a){return Math.asin(a)};c.prototype.fatan=function(a){return Math.atan(a)};c.prototype.fceil=function(a){return Math.ceil(a)};c.prototype.fcos=function(a){return Math.cos(a)};c.prototype.fexp=function(a){return Math.exp(a)};c.prototype.ffloor=function(a){return Math.floor(a)};
c.prototype.frnd=function(){return Math.random()};c.prototype.flog=function(a){return a>=0?Math.log(a):0};c.prototype.fsin=function(a){return Math.sin(a)};c.prototype.fsqrt=function(a){return a>=0?Math.sqrt(a):0};c.prototype.ftan=function(a){return Math.cos(a)==0?(Math.sin(a)>=0?1:-1)*Infinity:Math.tan(a)};c.prototype.fpow=function(a,b){return Math.pow(a,b)};d.prototype.scmp=function(a,b){return a==b?0:a<b?-1:1};d.prototype.slen=function(a){return a.length};d.prototype.smid=function(a,b,c){b=Math.min(a.length,
Math.max(b,0));return a.substr(b,b+Math.min(a.length-b,Math.max(c,0)))};d.prototype.scat=function(a,b){return(""+a).concat(""+b)};d.prototype.supr=function(a){return(""+a).toUpperCase()};d.prototype.slwr=function(a){return(""+a).toLowerCase()};d.prototype.sstr=function(a){return""+a};d.prototype.sval=function(a){return parseFloat(a)};d.prototype.sasc=function(a){return(a+" ").charCodeAt(0)};d.prototype.schr=function(a){return String.fromCharCode(parseInt(a))};var f=new e,g=new c,h=new d;this.lu=function(){return f};
this.fpu=function(){return g};this.su=function(){return h}};
function WindowInterrupt(b,e,d,c,a){b=a();switch(b){case 0:alert(a());break;case 1:b=a();a();a=prompt(b);c(a!=null&&a!=void 0?a:"");break;case 2:c(confirm(a())?!0:!1);break;default:throw Error("WindowInterrupt: invalid task: "+b);}}function PrinterInterrupt(b,e,d,c,a){e=a();switch(e){case 0:b.printer().print(a());break;default:throw Error("PrinterInterrupt: invalid task: "+e);}}
function AudioInterrupt(b,e,d,c,a){d=a();switch(d){case 0:c(e.audioData().createVoice(a()));break;case 1:e.audioData().destroyVoice(a());break;case 2:c=a();a=a();b.audio().play(e.audioData().getVoice(c),a);break;case 3:b.audio().stop(e.audioData().getVoice(a()));break;case 4:b.audio().pause(e.audioData().getVoice(a()));break;case 5:b.audio().resume(e.audioData().getVoice(a()));break;case 6:c=a();a=a();b.audio().setPosition(e.audioData().getVoice(c),a);break;case 7:c(b.audio().getPosition(e.audioData().getVoice(a())));
break;case 8:c=a();a=a();b.audio().setVolume(e.audioData().getVoice(c),a);break;case 9:c(b.audio().getVolume(e.audioData().getVoice(a())));break;case 10:c(b.audio().getDuration(e.audioData().getVoice(a())));break;case 11:c(b.audio().isPlaying(e.audioData().getVoice(a())));break;default:throw Error("AudioInterrupt: invalid task: "+d);}}
function VideoInterrupt(b,e,d,c,a){d=a();switch(d){case 0:c(b.video().canvasWidth());break;case 1:c(b.video().canvasHeight());break;case 2:break;case 3:break;case 4:b.video().enableDoubleBuffering();break;case 5:b.video().flip();break;case 6:b.video().cls();break;case 10:e=a();c=a();a=a();b.video().setColor(e,c,a);break;case 11:b.video().setAlpha(a());break;case 12:var c=a(),d=a(),f=a(),a=a();b.video().rectfill(c,d,f,a);break;case 13:c=a();d=a();f=a();a=a();b.video().rect(c,d,f,a);break;case 14:c=
a();d=a();e=a();b.video().circlefill(c,d,e);break;case 15:c=a();d=a();e=a();b.video().circle(c,d,e);break;case 16:c=a();d=a();e=a();a=a();b.video().line(c,d,e,a);break;case 17:e=a();f=a();c=a();d=a();a=a();b.video().textout(e,f,c,d,a);break;case 18:var g=a(),c=a(),d=a();b.video().drawImage(e.imageData().get(g),c,d);break;case 19:g=a();c=a();d=a();f=a();a=a();b.video().drawScaledImage(e.imageData().get(g),c,d,f,a);break;case 20:var g=a(),h=a(),i=a(),j=a(),k=a(),c=a(),d=a(),f=a(),a=a();b.video().drawClippedImage(e.imageData().get(g),
h,i,j,k,c,d,f,a);break;case 21:c(e.imageData().get(a()).width);break;case 22:c(e.imageData().get(a()).height);break;case 23:c=a();a=a();b.video().setTranslation(c,a);break;case 24:c=a();a=a();b.video().setScale(c,a);break;case 25:a=a();b.video().setRotation(a);break;case 26:a=a();b.video().setCompositeOperation(a);break;default:throw Error("VideoInterrupt: invalid task: "+d);}}function MouseInterrupt(b,e,d,c,a){b=a();switch(b){default:throw Error("MouseInterrupt: invalid task: "+b);}}
function KeyboardInterrupt(b,e,d,c,a){b=a();switch(b){default:throw Error("KeyboardInterrupt: invalid task: "+b);}}
function MemoryInterrupt(b,e,d,c,a){b=a();switch(b){case 0:b=a();c(d.tableExists(b));break;case 1:c(d.createTable());break;case 2:b=a();d.destroyTable(b);break;case 3:b=a();c(d.tableSize(b));break;case 4:b=a();e=a();c(d.tableEntryExists(b,e));break;case 5:b=a();e=a();c(d.removeTableEntry(b,e));break;case 6:b=a();e=a();c(d.getTableEntry(b,e));break;case 7:b=a();e=a();c=a();d.setTableEntry(b,e,c);break;case 8:b=a();c(d.cloneTable(b));break;case 9:b=a();c(d.getTableIterator(b));break;case 10:b=a();a=
a();c(d.tableIteratorIsValid(b,a));break;case 11:b=a();a=a();c(d.incrementTableIterator(b,a));break;case 12:b=a();a=a();c(d.getKeyFromTableIterator(b,a));break;case 13:b=a();a=a();c(d.getValueFromTableIterator(b,a));break;default:throw Error("MemoryInterrupt: invalid task: "+b);}}
function InterruptionManager(b,e,d){var c={3:MemoryInterrupt,4:WindowInterrupt,5:PrinterInterrupt,6:AudioInterrupt,7:VideoInterrupt,8:KeyboardInterrupt,9:MouseInterrupt},a=d.ram(),f=b.getCode("SP"),g=function(){return a.read(b.write(f,b.read(f)+1))},h=function(c){return a.write(1+b.write(f,b.read(f)-1),c)};this.run=function(a){if(typeof c[a]=="function")c[a](e,d.media(),d.tableManager(),h,g);else throw Error("Invalid interruption code: "+a);}};
function ControlUnit(k,p,t,u,l){var b={NOP:0,HALT:1,MOVC:2,MOVR:3,LOADC:4,LOADR:5,STOREC:6,STORER:7,JMPC:8,JMPR:9,LCMPC:10,LCMPR:11,FCMPC:12,FCMPR:13,SCMPC:14,SCMPR:15,JEC:16,JNEC:17,JLC:18,JLEC:19,JGC:20,JGEC:21,JER:22,JNER:23,JLR:24,JLER:25,JGR:26,JGER:27,PUSHC:28,PUSHR:29,POP:30,CALLC:31,CALLR:32,RET:33,INTC:34,INTR:35,LORC:36,LORR:37,LANDC:38,LANDR:39,LXORC:40,LXORR:41,LNOT:42,FADDC:43,FADDR:44,FSUBC:45,FSUBR:46,FMULC:47,FMULR:48,FDIVC:49,FDIVR:50,FMODC:51,FMODR:52,FNEG:53,FINT:54,FACOS:55,FASIN:56,
FATAN:57,FCEIL:58,FCOS:59,FEXP:60,FFLOOR:61,FRND:62,FLOG:63,FSIN:64,FSQRT:65,FTAN:66,SLEN:67,SLEFTC:68,SLEFTR:69,SRIGHTC:70,SRIGHTR:71,SCATC:72,SCATR:73,SUPR:74,SLWR:75,SSTR:76,SVAL:77,FPOWC:78,FPOWR:79,TYPE:80,SASC:81,SCHR:82,$:void 0},m=k.getCode("SP"),r=k.getCode("BP"),j=k.getCode("PC"),g=k.getCode("CPF"),c=k.bank,q=l.ram().read,n=l.ram().write,v=u.get,i=p.lu(),e=p.fpu(),h=p.su(),o=!1,s=new InterruptionManager(k,t,l),d={};d[b.NOP]=function(){};d[b.HALT]=function(){o=!0};d[b.MOVC]=function(a,b){c[a]=
b};d[b.MOVR]=function(a,b){c[a]=c[b]};d[b.LOADC]=function(a,b){c[a]=q(b)};d[b.LOADR]=function(a,b){c[a]=q(c[b])};d[b.STOREC]=function(a,b){n(b,c[a])};d[b.STORER]=function(a,b){n(c[b],c[a])};d[b.LCMPC]=function(a,b){c[g]=i.lcmp(c[a],b)};d[b.LCMPR]=function(a,b){c[g]=i.lcmp(c[a],c[b])};d[b.FCMPC]=function(a,b){c[g]=e.fcmp(c[a],b)};d[b.FCMPR]=function(a,b){c[g]=e.fcmp(c[a],c[b])};d[b.SCMPC]=function(a,b){c[g]=h.scmp(c[a],b)};d[b.SCMPR]=function(a,b){c[g]=h.scmp(c[a],c[b])};d[b.JMPC]=function(a){c[j]=
a};d[b.JMPR]=function(a){c[j]=c[a]};d[b.JEC]=function(a,f){d[b[c[g]==0?"JMPC":"NOP"]](a,f)};d[b.JNEC]=function(a,f){d[b[c[g]!=0?"JMPC":"NOP"]](a,f)};d[b.JLC]=function(a,f){d[b[c[g]<0?"JMPC":"NOP"]](a,f)};d[b.JLEC]=function(a,f){d[b[c[g]<=0?"JMPC":"NOP"]](a,f)};d[b.JGC]=function(a,f){d[b[c[g]>0?"JMPC":"NOP"]](a,f)};d[b.JGEC]=function(a,f){d[b[c[g]>=0?"JMPC":"NOP"]](a,f)};d[b.JER]=function(a,f){d[b[c[g]==0?"JMPR":"NOP"]](a,f)};d[b.JNER]=function(a,f){d[b[c[g]!=0?"JMPR":"NOP"]](a,f)};d[b.JLR]=function(a,
f){d[b[c[g]<0?"JMPR":"NOP"]](a,f)};d[b.JLER]=function(a,f){d[b[c[g]<=0?"JMPR":"NOP"]](a,f)};d[b.JGR]=function(a,f){d[b[c[g]>0?"JMPR":"NOP"]](a,f)};d[b.JGER]=function(a,f){d[b[c[g]>=0?"JMPR":"NOP"]](a,f)};d[b.PUSHC]=function(a){n(c[m]--,a)};d[b.PUSHR]=function(a){n(c[m]--,c[a])};d[b.POP]=function(a){c[a]=q(++c[m]);if(c[m]>c[r])throw Error("Stack overflow");};d[b.CALLC]=function(a){d[b.PUSHR](j,0);d[b.JMPC](a,0)};d[b.CALLR]=function(a){d[b.PUSHR](j,0);d[b.JMPR](a,0)};d[b.RET]=function(){d[b.POP](j,
0)};d[b.INTC]=function(a){s.run(a)};d[b.INTR]=function(a){s.run(c[a])};d[b.LORC]=function(a,b){c[a]=i.lor(c[a],b)};d[b.LORR]=function(a,b){c[a]=i.lor(c[a],c[b])};d[b.LANDC]=function(a,b){c[a]=i.land(c[a],b)};d[b.LANDR]=function(a,b){c[a]=i.land(c[a],c[b])};d[b.LXORC]=function(a,b){c[a]=i.lxor(c[a],b)};d[b.LXORR]=function(a,b){c[a]=i.lxor(c[a],c[b])};d[b.LNOT]=function(a){c[a]=i.lnot(c[a])};d[b.FADDC]=function(a,b){c[a]=e.fadd(c[a],b)};d[b.FADDR]=function(a,b){c[a]=e.fadd(c[a],c[b])};d[b.FSUBC]=function(a,
b){c[a]=e.fsub(c[a],b)};d[b.FSUBR]=function(a,b){c[a]=e.fsub(c[a],c[b])};d[b.FMULC]=function(a,b){c[a]=e.fmul(c[a],b)};d[b.FMULR]=function(a,b){c[a]=e.fmul(c[a],c[b])};d[b.FDIVC]=function(a,b){c[a]=e.fdiv(c[a],b)};d[b.FDIVR]=function(a,b){c[a]=e.fdiv(c[a],c[b])};d[b.FMODC]=function(a,b){c[a]=e.fmod(c[a],b)};d[b.FMODR]=function(a,b){c[a]=e.fmod(c[a],c[b])};d[b.FNEG]=function(a){c[a]=e.fneg(c[a])};d[b.FINT]=function(a){c[a]=e.fint(c[a])};d[b.FACOS]=function(a){c[a]=e.facos(c[a])};d[b.FASIN]=function(a){c[a]=
e.fasin(c[a])};d[b.FATAN]=function(a){c[a]=e.fatan(c[a])};d[b.FCEIL]=function(a){c[a]=e.fceil(c[a])};d[b.FCOS]=function(a){c[a]=e.fcos(c[a])};d[b.FEXP]=function(a){c[a]=e.fexp(c[a])};d[b.FFLOOR]=function(a){c[a]=e.ffloor(c[a])};d[b.FRND]=function(a){c[a]=e.frnd()};d[b.FLOG]=function(a){c[a]=e.flog(c[a])};d[b.FSIN]=function(a){c[a]=e.fsin(c[a])};d[b.FSQRT]=function(a){c[a]=e.fsqrt(c[a])};d[b.FTAN]=function(a){c[a]=e.ftan(c[a])};d[b.SLEN]=function(a){c[a]=h.slen(c[a])};d[b.SLEFTC]=function(a,b){c[a]=
h.smid(c[a],0,b)};d[b.SLEFTR]=function(a,b){c[a]=h.smid(c[a],0,c[b])};d[b.SRIGHTC]=function(a,b){c[a]=h.smid(c[a],c[a].length-b,b)};d[b.SRIGHTR]=function(a,b){c[a]=h.smid(c[a],c[a].length-c[b],c[b])};d[b.SCATC]=function(a,b){c[a]=h.scat(c[a],b)};d[b.SCATR]=function(a,b){c[a]=h.scat(c[a],c[b])};d[b.SUPR]=function(a){c[a]=h.supr(c[a])};d[b.SLWR]=function(a){c[a]=h.slwr(c[a])};d[b.SSTR]=function(a){c[a]=h.sstr(c[a])};d[b.SVAL]=function(a){c[a]=h.sval(c[a])};d[b.FPOWC]=function(a,b){c[a]=e.fpow(c[a],
b)};d[b.FPOWR]=function(a,b){c[a]=e.fpow(c[a],c[b])};d[b.TYPE]=function(a){c[a]=(typeof c[a]).toLowerCase()};d[b.SASC]=function(a){c[a]=h.sasc(c[a])};d[b.SCHR]=function(a){c[a]=h.schr(c[a])};this.reset=function(){o=!1;c[m]=l.ram().capacity()-1;c[r]=l.ram().capacity()-1;c[j]=0};this.programHasTerminated=function(){return o};this.getOpcode=function(a){if(typeof a!="string"||b[a]==void 0)throw Error("Illegal instruction");return b[a]};this.fetchDecodeExecute=function(){if(!o){var a=v(c[j]),b=d[a.opcode];
++c[j];b(a.operand1,a.operand2)}};this.reset()};
if(!window.requestAnimFrame)window.requestAnimFrame=function(){return window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
function Clock(a,c,h,j){function l(){(function m(){try{if(!e){for(var a=c;!b&&a--;)h(),++g;b=!1;d&&requestAnimFrame(m)}}catch(f){k.stop(),alert("FATAL ERROR:\n\n"+f.message)}})()}function f(){window.setTimeout(function(){try{if(!e){for(var a=c;!d&&a--;)h(),++g;d||f()}}catch(b){k.stop(),alert("FATAL ERROR:\n\n"+b.message)}},1E3/a)}if(typeof a!="number"||a<=0)throw Error("Clock error: invalid value for cycles per second");else if(typeof c!="number"||c<=0)throw Error("Clock error: invalid value for instructions per cycle");
else if(typeof h!="function")throw Error("Clock error: invalid callback");var k=this,g=0,i=0,e=!0,b=!1,d=!1;this.notify=function(a,c){switch(c.msg){case "enabled double buffering":d=!0;b=!1;l();break;case "disabled double buffering":b=d=!1;f();break;case "flipped":b=!0}};j!=null&&window.setInterval(function(){e||j.write(288,(new Date).getTime()-i)},10);this.getCyclesPerSecond=function(){return a};this.getInstructionsPerCycle=function(){return c};this.ticks=function(){return g};this.start=function(){b=
d=e=!1;i=(new Date).getTime();f()};this.stop=function(){e=!0;b=d=!1;g=i=0}};
function CPU(i,j,c,g,d){var h=new DPU,e=new Registers,f=new ControlUnit(e,h,c,g,d),b=new Clock(i,j,f.fetchDecodeExecute,d.ram());c.video().registerObserver(b);this.dpu=function(){return h};this.registers=function(){return e};this.controlUnit=function(){return f};this.clock=function(){return b};var a=!1;this.powerOn=function(){a||(b.start(),a=!0)};this.powerOff=function(){a&&(c.video().reset(),b.stop(),e.reset(),f.reset(),g.reset(),d.reset(),a=!1)};this.isTurnedOn=function(){return a}};
function RuntimeEngine(k,l,m){var g=new LoadingScreen,h=!1,c=null,b=null,e=null,a=null;this.loadGame=function(i,n){var d=[],j={};if(!h){h=!0;a!=null&&(a.powerOff(),delete a,a=null);c!=null&&(delete c,c=null);b!=null&&(delete b,b=null);e!=null&&(delete e,e=null);if(i==void 0)throw Error("Invalid game");d=i.program;j=i.media;if(d==void 0)throw Error("No program given");else if(d.length%3!=0)throw Error("Invalid program length");c=new InstructionMemory;b=new DataMemory(m);b.media().load(j,function(a){g.display(a.file,
1-a.remaining/a.total)},function(){g.display("",1);for(var f=0;f<d.length;f+=3)c.push(new Instruction(d[f+0],d[f+1],d[f+2]));c.push(new Instruction(1,0,0));e=new IO(b);a=new CPU(k,l,e,c,b);setTimeout(function(){g.clear();h=!1;n()},100)})}};this.powerOn=function(){if(a!=null)a.powerOn();else throw Error("Please load the program");};this.powerOff=function(){a!=null&&(a.powerOff(),b.media().release())}};
